FROM node:16-alpine as builder

COPY ./frontend /src

WORKDIR /src

RUN yarn install

RUN yarn build

FROM node:16-alpine

RUN yarn global add serve

COPY --from=BUILDER /src/build /

CMD serve -s /build