FROM node:16-alpine as builder

COPY ./frontend /src

WORKDIR /src

RUN yarn install --production=true

RUN yarn build

FROM node:16-alpine

RUN yarn global add serve

COPY --from=builder /src/build /build

CMD serve -s /build