FROM golang:1.17-alpine as builder

COPY go.mod go.sum /src/
COPY ./cmd /src/cmd
COPY ./internal /src/internal
WORKDIR /src

RUN go build cmd/main/main.go

FROM alpine:3.15

COPY --from=builder /src/main /

CMD /main