FROM node:16-alpine as builder

COPY ./frontend/package.json ./frontend/yarn.lock /src/

WORKDIR /src

RUN yarn install --production=true

COPY ./frontend /src

RUN yarn build

FROM node:16-alpine

RUN yarn global add serve

COPY --from=builder /src/build /build

CMD serve -s /build